version: '3.7'

services:
  worker:
    image: "node:14.15.1-alpine3.12"
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile.prod
      # target: production
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - VERSION=1.0
    # volumes are only required for live reloading and binding local directories
    # volumes:
    #   - /usr/src/app
    #   - /usr/app/node_modules
    # ports:
    #   - "3000:3000"
    tty: true
    command: "yarn start:prod"
    env_file:
      - .env
    networks:
      - webnet
    restart: always

networks:
  webnet: